/**************************************************************************************************
 * project
 * Description - Cce0202 - Credit Card Statement Upload
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.cce.cce0202;

import zebra.data.ParamEntity;

public interface Cce0202Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getUpload(ParamEntity paramEntity) throws Exception;
	public ParamEntity getBankAccountInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity getFile(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getInfoDataForDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getCcStatementDetail(ParamEntity paramEntity) throws Exception;

	public ParamEntity doUpload(ParamEntity paramEntity) throws Exception;
	public ParamEntity discardCcStatement(ParamEntity paramEntity) throws Exception;
	public ParamEntity doSave(ParamEntity paramEntity) throws Exception;
	public ParamEntity doDelete(ParamEntity paramEntity) throws Exception;
}