/**************************************************************************************************
 * project
 * Description - Sys0208 - User Management
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys0208;

import zebra.data.ParamEntity;

public interface Sys0208Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getActionContextMenu(ParamEntity paramEntity) throws Exception;
	public ParamEntity getEdit(ParamEntity paramEntity) throws Exception;
	public ParamEntity getUserDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getBankAccounts(ParamEntity paramEntity) throws Exception;

	public ParamEntity exeActionContextMenu(ParamEntity paramEntity) throws Exception;
	public ParamEntity saveUserDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity saveBankAccnts(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeDelete(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeExport(ParamEntity paramEntity) throws Exception;
}