/**************************************************************************************************
 * project
 * Description - Bau0204 - Announcement
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.bau.bau0204;

import zebra.data.ParamEntity;

public interface Bau0204Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getAttachedFile(ParamEntity paramEntity) throws Exception;
}