/**************************************************************************************************
 * project
 * Description - Sys0802 - Financial Period Type
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys0802;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseBiz;
import project.common.module.datahelper.DataHelper;
import project.conf.resource.ormapper.dao.ProjectDummy.ProjectDummyDao;
import project.conf.resource.ormapper.dao.SysFinancialPeriod.SysFinancialPeriodDao;
import project.conf.resource.ormapper.dto.oracle.SysFinancialPeriod;
import zebra.data.DataSet;
import zebra.data.ParamEntity;
import zebra.data.QueryAdvisor;
import zebra.exception.FrameworkException;
import zebra.util.CommonUtil;
import zebra.util.ConfigUtil;

public class Sys0802BizImpl extends BaseBiz implements Sys0802Biz {
	@Autowired
	private SysFinancialPeriodDao sysFinancialPeriodDao;
	@Autowired
	private ProjectDummyDao projectDummyDao;

	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception {
		try {
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity getList(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		QueryAdvisor queryAdvisor = paramEntity.getQueryAdvisor();

		try {
			queryAdvisor.setRequestDataSet(requestDataSet);
			queryAdvisor.setPagination(true);

			paramEntity.setAjaxResponseDataSet(sysFinancialPeriodDao.getPeriodDataSetByCriteria(queryAdvisor));
			paramEntity.setTotalResultRows(queryAdvisor.getTotalResultRows());
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity getEdit(ParamEntity paramEntity) throws Exception {
		try {
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity getFinancialPeriod(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		String periodYear = requestDataSet.getValue("periodYear");
		String quarterCode = requestDataSet.getValue("quarterCode");
		DataSet financialPeriod;

		try {
			financialPeriod = sysFinancialPeriodDao.getDataSetByPeriodYearAndCode(periodYear, quarterCode);
			financialPeriod.addColumn("INSERT_USER_NAME", DataHelper.getUserNameById(financialPeriod.getValue("INSERT_USER_ID")));
			financialPeriod.addColumn("UPDATE_USER_NAME", DataHelper.getUserNameById(financialPeriod.getValue("UPDATE_USER_ID")));

			paramEntity.setAjaxResponseDataSet(financialPeriod);
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity doAutoGenerate(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		QueryAdvisor queryAdvisor = new QueryAdvisor();
		HttpSession session = paramEntity.getSession();
		String dateFormat = ConfigUtil.getProperty("format.date.java");
		String loggedInUserId = (String)session.getAttribute("UserId");
		String periodYear = requestDataSet.getValue("periodYearForAutoGen");
		String quarterCode = requestDataSet.getValue("quarterCodeForAutoGen");
		SysFinancialPeriod sysFinancialPeriod = new SysFinancialPeriod();
		DataSet financialPeriod = new DataSet();
		int result = -1;

		try {
			queryAdvisor.setObject("year", periodYear);
			queryAdvisor.setObject("quarterCode", quarterCode);
			financialPeriod = projectDummyDao.getFinacialQuarter(queryAdvisor);

			if (CommonUtil.isBlank(quarterCode)) {
				for (int i=0; i<financialPeriod.getRowCnt(); i++) {
					sysFinancialPeriod.setPeriodYear(periodYear);
					sysFinancialPeriod.setQuarterCode(financialPeriod.getValue(i, "QUARTER_CODE"));
					sysFinancialPeriod.setFinancialYear(financialPeriod.getValue(i, "FINANCIAL_YEAR"));
					sysFinancialPeriod.setQuarterName(financialPeriod.getValue(i, "QUARTER_NAME"));
					sysFinancialPeriod.setDateFrom(CommonUtil.toDate(financialPeriod.getValue(i, "QUARTER_DATE_FROM"), dateFormat));
					sysFinancialPeriod.setDateTo(CommonUtil.toDate(financialPeriod.getValue(i, "QUARTER_DATE_TO"), dateFormat));
					sysFinancialPeriod.setInsertUserId(loggedInUserId);
					sysFinancialPeriod.setInsertDate(CommonUtil.getSysdateAsDate());

					result = sysFinancialPeriodDao.insert(sysFinancialPeriod);
				}
			} else {
				sysFinancialPeriod.setPeriodYear(periodYear);
				sysFinancialPeriod.setQuarterCode(quarterCode);
				sysFinancialPeriod.setFinancialYear(financialPeriod.getValue("FINANCIAL_YEAR"));
				sysFinancialPeriod.setQuarterName(financialPeriod.getValue("QUARTER_NAME"));
				sysFinancialPeriod.setDateFrom(CommonUtil.toDate(financialPeriod.getValue("QUARTER_DATE_FROM"), dateFormat));
				sysFinancialPeriod.setDateTo(CommonUtil.toDate(financialPeriod.getValue("QUARTER_DATE_TO"), dateFormat));
				sysFinancialPeriod.setInsertUserId(loggedInUserId);
				sysFinancialPeriod.setInsertDate(CommonUtil.getSysdateAsDate());

				result = sysFinancialPeriodDao.insert(sysFinancialPeriod);
			}

			if (result <= 0) {
				throw new FrameworkException("E801", getMessage("E801", paramEntity));
			}

			paramEntity.setSuccess(true);
			paramEntity.setMessage("I801", getMessage("I801", paramEntity));
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity doSave(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		HttpSession session = paramEntity.getSession();
		String dateFormat = ConfigUtil.getProperty("format.date.java");
		String loggedInUserId = (String)session.getAttribute("UserId");
		String periodYear = requestDataSet.getValue("periodYear");
		String quarterCode = requestDataSet.getValue("quarterCode");
		SysFinancialPeriod sysFinancialPeriod = new SysFinancialPeriod();
		DataSet financialPeriod;
		int result = -1;

		try {
			sysFinancialPeriod = sysFinancialPeriodDao.getFinancialPeriodByPeriodYearAndCode(periodYear, quarterCode);
			if (sysFinancialPeriod == null || CommonUtil.isBlank(sysFinancialPeriod.getPeriodYear())) {
				sysFinancialPeriod.setPeriodYear(requestDataSet.getValue("periodYear"));
				sysFinancialPeriod.setQuarterCode(requestDataSet.getValue("quarterCode"));
				sysFinancialPeriod.setFinancialYear(requestDataSet.getValue("financialYearFrom")+"-"+requestDataSet.getValue("financialYearTo"));
				sysFinancialPeriod.setQuarterName(requestDataSet.getValue("quarterName"));
				sysFinancialPeriod.setDateFrom(CommonUtil.toDate(requestDataSet.getValue("dateFrom"), dateFormat));
				sysFinancialPeriod.setDateTo(CommonUtil.toDate(requestDataSet.getValue("dateTo"), dateFormat));
				sysFinancialPeriod.setInsertUserId(loggedInUserId);
				sysFinancialPeriod.setInsertDate(CommonUtil.getSysdateAsDate());

				result = sysFinancialPeriodDao.insert(sysFinancialPeriod);
			} else {
				sysFinancialPeriod.setFinancialYear(requestDataSet.getValue("financialYearFrom")+"-"+requestDataSet.getValue("financialYearTo"));
				sysFinancialPeriod.setQuarterName(requestDataSet.getValue("quarterName"));
				sysFinancialPeriod.setDateFrom(CommonUtil.toDate(requestDataSet.getValue("dateFrom"), dateFormat));
				sysFinancialPeriod.setDateTo(CommonUtil.toDate(requestDataSet.getValue("dateTo"), dateFormat));
				sysFinancialPeriod.setUpdateUserId(loggedInUserId);
				sysFinancialPeriod.setUpdateDate(CommonUtil.getSysdateAsDate());
				sysFinancialPeriod.addUpdateColumnFromField();

				result = sysFinancialPeriodDao.updateWithKey(sysFinancialPeriod, periodYear, quarterCode);
			}

			if (result <= 0) {
				throw new FrameworkException("E801", getMessage("E801", paramEntity));
			}

			financialPeriod = sysFinancialPeriodDao.getDataSetByPeriodYearAndCode(periodYear, quarterCode);
			financialPeriod.addColumn("INSERT_USER_NAME", DataHelper.getUserNameById(financialPeriod.getValue("INSERT_USER_ID")));
			financialPeriod.addColumn("UPDATE_USER_NAME", DataHelper.getUserNameById(financialPeriod.getValue("UPDATE_USER_ID")));

			paramEntity.setAjaxResponseDataSet(financialPeriod);
			paramEntity.setSuccess(true);
			paramEntity.setMessage("I801", getMessage("I801", paramEntity));
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity doDelete(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		String periodYear = requestDataSet.getValue("periodYear");
		String quarterCode = requestDataSet.getValue("quarterCode");
		String chkForDel = requestDataSet.getValue("chkForDel");
		String keyIds[] = CommonUtil.splitWithTrim(chkForDel, ConfigUtil.getProperty("delimiter.record"));
		int result = 0;

		try {
			if (CommonUtil.isBlank(periodYear) && CommonUtil.isBlank(quarterCode)) {
				result = sysFinancialPeriodDao.deleteWithKeys(keyIds);
			} else {
				result = sysFinancialPeriodDao.deleteWithKey(periodYear, quarterCode);
			}

			if (result <= 0) {
				throw new FrameworkException("E801", getMessage("E801", paramEntity));
			}

			paramEntity.setSuccess(true);
			paramEntity.setMessage("I801", getMessage("I801", paramEntity));
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}
}