<%/************************************************************************************************
* Description - Cce0208 - Cash Expenses
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	String cashExpenseId = requestDataSet.getValue("cashExpenseId");
	String dateFormat = ConfigUtil.getProperty("format.date.java");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var cashExpenseId = "<%=cashExpenseId%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table class="tblEdit">
		<colgroup>
			<col width="30%"/>
			<col width="70%"/>
		</colgroup>
		<tr>
			<th class="thEdit Rt mandatory">Date</th>
			<td class="tdEdit">
				<ui:text name="procDate" className="Ct hor" style="width:90px" checkName="Date" option="date" options="mandatory"/>
				<ui:icon id="icnProcDate" className="fa-calendar hor"/>
			</td>
		</tr>
		<tr>
			<th class="thEdit Rt mandatory">Category</th>
			<td class="tdEdit"><ui:deSelect name="category" codeType="SubReconCategory" parentCategoryId="0200" checkName="Category" caption="==Select==" options="mandatory" attribute="data-width:100%"/></td>
		</tr>
		<tr>
			<th class="thEdit Rt mandatory">Gross Amount</th>
			<td class="tdEdit"><ui:text name="grossAmt" className="Rt numeric" checkName="Gross Amount" style="width:120px" option="numeric" options="mandatory"/></td>
		</tr>
		<tr>
			<th class="thEdit Rt">GST Amount</th>
			<td class="tdEdit"><ui:text name="gstAmt" className="Rt numeric" style="width:120px" option="numeric"/></td>
		</tr>
		<tr>
			<th class="thEdit Rt">Net Amount</th>
			<td class="tdEdit"><ui:text name="netAmt" className="Rt numeric" style="width:120px" option="numeric" status="disabled"/></td>
		</tr>
		<tr>
			<th class="thEdit Rt">Particular</th>
			<td class="tdEdit"><ui:txa name="procDescription" style="height:66px"/></td>
		</tr>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>