<%/************************************************************************************************
* Description - Sys0804 - Reconciliation Category Mgmt.
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	DataSet mainCategory = (DataSet)paramEntity.getObject("mainCategory");
	String mode = requestDataSet.getValue("mode");
	String categoryId = requestDataSet.getValue("categoryId");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var mode = "<%=mode%>";
var categoryId = "<%=categoryId%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea">
</div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table class="tblEdit">
		<colgroup>
			<col width="20%"/>
			<col width="30%"/>
			<col width="20%"/>
			<col width="30%"/>
		</colgroup>
		<tr>
			<th class="thEdit Rt">Category ID</th>
			<td class="tdEdit"><ui:text name="categoryId" status="display"/></td>
			<th class="thEdit Rt">Main Category</th>
			<td class="tdEdit">
				<ui:select name="parentCategoryId">
				</ui:select>
			</td>
		</tr>
		<tr>
			<th class="thEdit Rt mandatory">Category Name</th>
			<td class="tdEdit" colspan="3"><ui:text name="categoryName" checkName="Category Name" options="mandatory"/></td>
		</tr>
		<tr>
			<th class="thEdit rt">Account Code</th>
			<td class="tdEdit"><ui:text name="accountCode" className="Ct"/></td>
			<th class="thEdit rt">Sort Order</th>
			<td class="tdEdit"><ui:text name="sortOrder" className="Ct"/></td>
		</tr>
		<tr>
			<th class="thEdit rt">Is GST Apply</th>
			<td class="tdEdit"><ui:ccradio name="isApplyGst" codeType="SIMPLE_YN" selectedValue="N" isCustomised="Y" status="disabled"/></td>
			<th class="thEdit rt">GST Percentage</th>
			<td class="tdEdit"><ui:text name="gstPercentage" className="Rt" option="numeric" status="disabled"/></td>
		</tr>
		<tr>
			<th class="thEdit rt">Last Updated By</th>
			<td class="tdEdit"><ui:text name="lastUpdatedBy" status="display"/></td>
			<th class="thEdit rt">Last Updated Date</th>
			<td class="tdEdit"><ui:text name="lastUpdatedDate" status="display"/></td>
		</tr>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>