/**************************************************************************************************
 * project
 * Description - Bsm0204 - Bank Statement Allocation
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.bsm.bsm0204;

import zebra.data.ParamEntity;

public interface Bsm0204Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getReconCategoryDataSet(ParamEntity paramEntity) throws Exception;
	public ParamEntity getSubReconCategory(ParamEntity paramEntity) throws Exception;
	public ParamEntity getEdit(ParamEntity paramEntity) throws Exception;

	public ParamEntity doSave(ParamEntity paramEntity) throws Exception;
	public ParamEntity doDelete(ParamEntity paramEntity) throws Exception;
	public ParamEntity getBatchApplication(ParamEntity paramEntity) throws Exception;
	public ParamEntity doBatchApplication(ParamEntity paramEntity) throws Exception;
}