/**************************************************************************************************
 * project
 * Description - Bsm0202 - Bank Transaction
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.bsm.bsm0202;

import zebra.data.ParamEntity;

public interface Bsm0202Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getUpload(ParamEntity paramEntity) throws Exception;
	public ParamEntity getBankAccountInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity getFile(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getInfoDataForDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getBankStatementDetail(ParamEntity paramEntity) throws Exception;

	public ParamEntity doUpload(ParamEntity paramEntity) throws Exception;
	public ParamEntity discardBankStatement(ParamEntity paramEntity) throws Exception;
	public ParamEntity doSave(ParamEntity paramEntity) throws Exception;
	public ParamEntity doDelete(ParamEntity paramEntity) throws Exception;
}