/**************************************************************************************************
 * project
 * Description - Pro0202 - Payroll Service
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.pro.pro0202;

import zebra.data.ParamEntity;

public interface Pro0202Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;

	public ParamEntity doSave(ParamEntity paramEntity) throws Exception;
}