<%/************************************************************************************************
* Description - Sys0402 - Menu
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet resultDataSet = (DataSet)paramEntity.getRequestDataSet();
	SysMenu sysMenu = (SysMenu)paramEntity.getObject("sysMenu");
	String menuLevel = (String)paramEntity.getObject("menuLevel");
	String menuPath = (String)paramEntity.getObject("menuPath");
	String deletable = (String)paramEntity.getObject("deletable");
	String dateFormat = ConfigUtil.getProperty("format.date.java");
	String deleteStatus = "";
	if (CommonUtil.equalsIgnoreCase(deletable, "false")) {
		deleteStatus = "disabled";
	}
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var deleteStatus = "<%=deleteStatus%>";
var paramValue = "<%=resultDataSet.getValue("paramValue")%>";
var menuId = "<%=sysMenu.getMenuId()%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnEdit" caption="button.com.edit" iconClass="fa-edit"/>
			<ui:button id="btnDelete" caption="button.com.delete" iconClass="fa-save" status="<%=deleteStatus%>"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table class="tblEdit">
		<colgroup>
			<col width="20%"/>
			<col width="30%"/>
			<col width="20%"/>
			<col width="30%"/>
		</colgroup>
		<tr>
			<th class="thEdit rt"><mc:msg key="sys0402.header.menuLevel"/></th>
			<td class="tdEdit"><%=menuLevel%></td>
			<th class="thEdit rt"><mc:msg key="sys0402.header.menuPath"/></th>
			<td class="tdEdit"><%=menuPath%></td>
		</tr>
		<tr>
			<th class="thEdit rt"><mc:msg key="sys0402.header.menuId"/></th>
			<td class="tdEdit"><%=sysMenu.getMenuId()%></td>
			<th class="thEdit rt"><mc:msg key="sys0402.header.menuUrl"/></th>
			<td class="tdEdit"><%=sysMenu.getMenuUrl()%></td>
		</tr>
		<tr>
			<th class="thEdit rt"><mc:msg key="sys0402.header.sortOrder"/></th>
			<td class="tdEdit"><%=sysMenu.getSortOrder()%></td>
			<th class="thEdit rt"><mc:msg key="sys0402.header.isActive"/></th>
			<td class="tdEdit"><%=sysMenu.getIsActive()%></td>
		</tr>
		<tr>
			<th class="thEdit rt"><mc:msg key="sys0402.header.menuNameEn"/></th>
			<td class="tdEdit" colspan="3"><%=sysMenu.getMenuNameEn()%></td>
		</tr>
		<tr>
			<th class="thEdit rt"><mc:msg key="sys0402.header.menuNameKo"/></th>
			<td class="tdEdit" colspan="3"><%=sysMenu.getMenuNameKo()%></td>
		</tr>
		<tr>
			<th class="thEdit rt"><mc:msg key="sys0402.header.description"/></th>
			<td class="tdEdit" colspan="3"><%=sysMenu.getDescription()%></td>
		</tr>
		<tr>
			<th class="thEdit rt"><mc:msg key="page.com.insertUser"/></th>
			<td class="tdEdit"><%=sysMenu.getInsertUserName()%></td>
			<th class="thEdit rt"><mc:msg key="page.com.insertDate"/></th>
			<td class="tdEdit"><%=CommonUtil.toString(sysMenu.getInsertDate(), dateFormat)%></td>
		</tr>
		<tr>
			<th class="thEdit rt"><mc:msg key="page.com.updateUser"/></th>
			<td class="tdEdit"><%=sysMenu.getUpdateUserName()%></td>
			<th class="thEdit rt"><mc:msg key="page.com.updateDate"/></th>
			<td class="tdEdit"><%=CommonUtil.toString(sysMenu.getUpdateDate(), dateFormat)%></td>
		</tr>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>