<%/************************************************************************************************
* Description - Sys0402 - Menu
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	DataSet resultDataSet = (DataSet)paramEntity.getObject("resultDataSet");
	SysMenu sysMenu = (SysMenu)paramEntity.getObject("sysMenu");
	String menuLevel = (String)paramEntity.getObject("menuLevel");
	String menuPath = (String)paramEntity.getObject("menuPath");
	String deletable = (String)paramEntity.getObject("deletable");
	String dateFormat = ConfigUtil.getProperty("format.date.java");
	String deleteStatus = "";
	if (CommonUtil.equalsIgnoreCase(deletable, "false")) {
		deleteStatus = "disabled";
	}
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table class="tblEdit">
		<colgroup>
			<col width="20%"/>
			<col width="30%"/>
			<col width="20%"/>
			<col width="30%"/>
		</colgroup>
		<tr>
			<th class="thEdit rt"><mc:msg key="sys0402.header.menuLevel"/></th>
			<td class="tdEdit"><ui:text name="menuLevel" value="<%=menuLevel%>" status="display"/></td>
			<th class="thEdit rt"><mc:msg key="sys0402.header.menuPath"/></th>
			<td class="tdEdit"><ui:text name="menuPath" value="<%=menuPath%>" status="display"/></td>
		</tr>
		<tr>
			<th class="thEdit rt"><mc:msg key="sys0402.header.menuId"/></th>
			<td class="tdEdit"><ui:text name="menuId" value="<%=sysMenu.getMenuId()%>" status="display"/></td>
			<th class="thEdit rt mandatory"><mc:msg key="sys0402.header.menuUrl"/></th>
			<td class="tdEdit"><ui:text name="menuUrl" value="<%=sysMenu.getMenuUrl()%>" checkName="sys0402.header.menuUrl" options="mandatory"/></td>
		</tr>
		<tr>
			<th class="thEdit rt mandatory"><mc:msg key="sys0402.header.sortOrder"/></th>
			<td class="tdEdit"><ui:text name="sortOrder" value="<%=sysMenu.getSortOrder()%>" checkName="sys0402.header.sortOrder" options="mandatory" option="numeric"/></td>
			<th class="thEdit rt"><mc:msg key="sys0402.header.isActive"/></th>
			<td class="tdEdit"><ui:ccradio name="isActive" codeType="SIMPLE_YN" selectedValue="<%=sysMenu.getIsActive()%>"/></td>
		</tr>
		<tr>
			<th class="thEdit rt mandatory"><mc:msg key="sys0402.header.menuNameEn"/></th>
			<td class="tdEdit" colspan="3"><ui:text name="menuNameEn" value="<%=sysMenu.getMenuNameEn()%>" checkName="sys0402.header.menuNameEn" options="mandatory"/></td>
		</tr>
		<tr>
			<th class="thEdit rt mandatory"><mc:msg key="sys0402.header.menuNameKo"/></th>
			<td class="tdEdit" colspan="3"><ui:text name="menuNameKo" value="<%=sysMenu.getMenuNameKo()%>" checkName="sys0402.header.menuNameKo" options="mandatory"/></td>
		</tr>
		<tr>
			<th class="thEdit rt"><mc:msg key="sys0402.header.description"/></th>
			<td class="tdEdit" colspan="3"><ui:text name="description" value="<%=sysMenu.getDescription()%>" checkName="sys0402.header.description"/></td>
		</tr>
		<tr>
			<th class="thEdit rt"><mc:msg key="page.com.insertUser"/></th>
			<td class="tdEdit"><ui:text name="insertUser" value="<%=sysMenu.getUpdateUserName()%>" status="display"/></td>
			<th class="thEdit rt"><mc:msg key="page.com.insertDate"/></th>
			<td class="tdEdit"><ui:text name="insertDate" value="<%=CommonUtil.toString(sysMenu.getUpdateDate(), dateFormat)%>" status="display"/></td>
		</tr>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>