<%/************************************************************************************************
* Description - Sys0402 - Menu
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	DataSet dsMenu = MenuManager.getMenuDataSet();
	DataSet dsMenu1 = MenuManager.getMenuDataSetByLevel(1);
	DataSet dsMenu2 = MenuManager.getMenuDataSetByLevel(2);
	SysUser sysUser = (SysUser)session.getAttribute("SysUser");
	String dateFormat = ConfigUtil.getProperty("format.date.java");
	String langCode = CommonUtil.upperCase((String)session.getAttribute("langCode"));
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
#liDummy {display:none;}
#divDataArea.areaContainerPopup {padding-top:0px;}
.dummyMenu {list-style:none;margin-top:4px;}
.dragHandler, .dragHandler > i {cursor:move;}
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var dsMenu = commonJs.getDataSetFromJavaDataSet("<%=dsMenu.toStringForJs()%>");
var dsMenu2 = commonJs.getDataSetFromJavaDataSet("<%=dsMenu2.toStringForJs()%>");
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea" class="areaContainerPopup">
	<div class="panel panel-default">
		<div class="panel-body">
			<div id="divMenuLevel" style="float:left;padding-right:4px;">
				<label for="menuLevel" class="lblEn hor"><mc:msg key="sys0402.header.menuLevel"/></label>
				<ui:ccselect name="menuLevel" codeType="MENU_LEVEL"/>
			</div>
			<div class="horGap70"></div>
			<div id="divLevel1" style="float:left;display:none;">
				<label for="level1" class="lblEn hor"><mc:msg key="sys0402.header.level1"/></label>
				<ui:select name="level1">
<%
				for (int i=0; i<dsMenu1.getRowCnt(); i++) {
					if (!CommonUtil.equals(dsMenu1.getValue(i, "MENU_ID"), "QM")) {
%>
					<ui:seloption value="<%=dsMenu1.getValue(i, \"MENU_ID\")%>" text="<%=dsMenu1.getValue(i, \"MENU_ID\")%>"/>
<%
					}
				}
%>
				</ui:select>
			</div>
			<div class="horGap30"></div>
			<div id="divLevel2" style="float:left;display:none;">
				<label for="level2" class="lblEn hor"><mc:msg key="sys0402.header.level2"/></label>
				<select id="level2" name="level2" class="bootstrapSelect"></select>
			</div>
		</div>
	</div>
</div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<ul id="ulMenuHolder"></ul>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
<li id="liDummy" class="dummyMenu">
	<table class="tblEdit">
		<colgroup>
			<col width="3%"/>
			<col width="15%"/>
			<col width="*"/>
			<col width="15%"/>
		</colgroup>
		<tr>
			<th id="thDragHander" class="thEdit Ct dragHandler" title="<mc:msg key="sys0402.msg.drag"/>"><ui:icon id="iDragHandler" className="fa-lg fa-sort"/></th>
			<td class="tdEdit"><ui:text name="menuId" status="display"/></td>
			<td class="tdEdit"><ui:text name="menuName" status="display"/></td>
			<td class="tdEdit"><ui:text name="sortOrder" status="display"/></td>
		</tr>
	</table>
</li>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>