/**************************************************************************************************
 * project
 * Description - Ads0204 - Invoice Management
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.ads.ads0204;

import zebra.data.ParamEntity;

public interface Ads0204Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getEdit(ParamEntity paramEntity) throws Exception;
	public ParamEntity getInvoiceNumber(ParamEntity paramEntity) throws Exception;
	public ParamEntity getMyInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity getOrgInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity getInvoiceMasterInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity getInvoiceDetailInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity getQuotationMasterInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity getQuotationDetailInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity getBankAccountInfo(ParamEntity paramEntity) throws Exception;

	public ParamEntity doRemoveLogo(ParamEntity paramEntity) throws Exception;
	public ParamEntity doSave(ParamEntity paramEntity) throws Exception;
	public ParamEntity doDelete(ParamEntity paramEntity) throws Exception;
	public ParamEntity getPreview(ParamEntity paramEntity) throws Exception;
	public ParamEntity doExport(ParamEntity paramEntity) throws Exception;
}