/**************************************************************************************************
 * project
 * Description - Sys0206 - Organisation Management
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys0206;

import zebra.data.ParamEntity;

public interface Sys0206Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getEdit(ParamEntity paramEntity) throws Exception;
	public ParamEntity getOrgDetail(ParamEntity paramEntity) throws Exception;

	public ParamEntity saveOrgDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeDelete(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeExport(ParamEntity paramEntity) throws Exception;
}