<%/************************************************************************************************
* Description - Ads0204 - Invoice Management
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	String invoiceId = requestDataSet.getValue("invoiceId");
	String dateFormat = "dd/MM/yyyy", numberFormat = "#,##0.00";
	UsrInvoice uin = (UsrInvoice)paramEntity.getObject("usrInvoice");
	DataSet dtl = (DataSet)paramEntity.getObject("invoiceDetail");
	String logoPath = uin.getProviderLogoPath();
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var invoiceId = "<%=invoiceId%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnPrint" caption="Print" iconClass="fa-print"/>
			<ui:button id="btnExport" caption="Download PDF" iconClass="fa-download"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<div class="verGap10"></div>
	<table class="tblDefault">
		<colgroup>
			<col width="50%"/>
			<col width="50%"/>
		</colgroup>
		<tr>
			<td class="tdDefault Lt" style="vertical-align:top;border-bottom:2px solid #DDDDDD;">
				<table class="tblDefault withPadding">
					<tr>
						<td class="tdDefault Lt" style="height:88px;">
<%
						if (CommonUtil.isNotBlank(logoPath)) {
%>
							<ui:img src="<%=logoPath%>" style="width:250px;height:80px;" status="display"/>
<%
						}
%>
						</td>
					</tr>
					<tr>
						<td class="tdDefault Lt" style="font-size:14px;font-weight:bold;"><%=uin.getProviderName()%></td>
					</tr>
				</table>
			</td>
			<td class="tdDefault Rt" style="vertical-align:top;border-bottom:2px solid #DDDDDD;">
				<table class="tblDefault withPadding">
					<colgroup>
						<col width="*"/>
						<col width="27%"/>
					</colgroup>
					<tr>
						<td class="tdDefault Rt" colspan="2" style="vertical-align:top;font-size:16px;font-weight:bold;height:48px;">Invoice</td>
					</tr>
					<tr>
						<th class="thDefault Rt">Invoice Date</th>
						<td class="tdDefault Rt"><%=CommonUtil.toString(uin.getIssueDate(), dateFormat)%></td>
					</tr>
					<tr>
						<th class="thDefault Rt">Invoice Number</th>
						<td class="tdDefault Rt"><%=uin.getInvoiceNumber()%></td>
					</tr>
					<tr>
						<th class="thDefault Rt">Due Date</th>
						<td class="tdDefault Rt"><%=CommonUtil.toString(uin.getPaymentDueDate(), dateFormat)%></td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
	<div class="verGap10"></div>
	<div style="float:left;width:49%;">
		<table class="tblDefault withPadding">
			<tr>
				<td class="thDefault Lt"><font style="font-weight:bold;font-size:12px">Bill To :</font></td>
			</tr>
			<tr>
				<td class="tdDefault Lt"><font style="font-weight:bold">Name : </font><%=uin.getClientName()%></td>
			</tr>
			<tr>
				<td class="tdDefault Lt"><font style="font-weight:bold">Tel : </font><%=CommonUtil.getFormatString(uin.getClientTelephone(), "?? ???? ????")%></td>
			</tr>
			<tr>
				<td class="tdDefault Lt"><font style="font-weight:bold">Mobile : </font><%=CommonUtil.getFormatString(uin.getClientMobile(), "???? ??? ???")%></td>
			</tr>
			<tr>
				<td class="tdDefault Lt"><font style="font-weight:bold">Email : </font><%=uin.getClientEmail()%></td>
			</tr>
			<tr>
				<td class="tdDefault Lt"><font style="font-weight:bold">Address : </font><%=uin.getClientAddress()%></td>
			</tr>
		</table>
	</div>
	<div style="float:right;width:50%;">
		<table class="tblDefault withPadding">
			<tr>
				<th class="thDefault Rt"><font style="font-weight:bold;font-size:12px">Issued By :</font></th>
			</tr>
			<tr>
				<td class="tdDefault Rt"><font style="font-weight:bold">Name : </font><%=uin.getProviderName()%></td>
			</tr>
			<tr>
				<td class="tdDefault Rt"><font style="font-weight:bold">ABN : </font><%=CommonUtil.getFormatString(uin.getProviderAbn(), "?? ??? ??? ???")%></td>
			</tr>
<%
			if (CommonUtil.isNotBlank(uin.getProviderAcn())) {
%>
			<tr>
				<td class="tdDefault Rt"><font style="font-weight:bold">ACN : </font><%=CommonUtil.getFormatString(uin.getProviderAcn(), "??? ??? ???")%></td>
			</tr>
<%
			}
%>
			<tr>
				<td class="tdDefault Rt"><font style="font-weight:bold">Tel : </font><%=CommonUtil.getFormatString(uin.getProviderTelephone(), "?? ???? ????")%></td>
			</tr>
			<tr>
				<td class="tdDefault Rt"><font style="font-weight:bold">Mobile : </font><%=CommonUtil.getFormatString(uin.getProviderMobile(), "???? ??? ???")%></td>
			</tr>
			<tr>
				<td class="tdDefault Rt"><font style="font-weight:bold">Email : </font><%=uin.getProviderEmail()%></td>
			</tr>
			<tr>
				<td class="tdDefault Rt"><font style="font-weight:bold">Address : </font><%=uin.getProviderAddress()%></td>
			</tr>
		</table>
	</div>
	<div class="verGap10"></div>
	<table id="tblGrid" class="tblGrid sort autosort" style="border:0px">
		<colgroup>
			<col width="*"></col>
			<col width="14%"></col>
			<col width="14%"></col>
			<col width="14%"></col>
		</colgroup>
		<thead>
			<tr class="noStripe">
				<th class="thGrid">Description</th>
				<th class="thGrid">Unit</th>
				<th class="thGrid">Price</th>
				<th class="thGrid">Amount</th>
			</tr>
		</thead>
		<tbody>
<%
	if (dtl.getRowCnt() > 0) {
		for (int i=0; i<dtl.getRowCnt(); i++) {
%>
			<tr class="noStripe">
				<td class="tdGrid Lt"><%=dtl.getValue(i, "DESCRIPTION")%></td>
				<td class="tdGrid Rt"><%=CommonUtil.getNumberMask(dtl.getValue(i, "UNIT"), numberFormat)%></td>
				<td class="tdGrid Rt"><%=CommonUtil.getNumberMask(dtl.getValue(i, "AMT_PER_UNIT"), numberFormat)%></td>
				<td class="tdGrid Rt"><%=CommonUtil.getNumberMask(dtl.getValue(i, "ITEM_AMT"), numberFormat)%></td>
			</tr>
<%
		}
	} else {
%>
			<tr class="noStripe">
				<td class="tdGrid Ct" colspan="4">&nbsp;</td>
			</tr>
<%
	}
%>
			<tr class="noStripe">
				<td class="tdGrid Rt" colspan="3" style="border:0px;font-weight:bold;">Sub Total</td>
				<td class="tdGrid Rt"><%=CommonUtil.getNumberMask(uin.getNetAmt(), numberFormat)%></td>
			</tr>
			<tr class="noStripe">
				<td class="tdGrid Rt" colspan="3" style="border:0px;font-weight:bold;">GST</td>
				<td class="tdGrid Rt"><%=CommonUtil.getNumberMask(uin.getGstAmt(), numberFormat)%></td>
			</tr>
			<tr class="noStripe">
				<td class="tdGrid Rt" colspan="3" style="border:0px;font-weight:bold;">Total Amount Due</td>
				<td class="tdGrid Rt"><%=CommonUtil.getNumberMask(uin.getTotalAmt(), numberFormat)%></td>
			</tr>
		</tbody>
	</table>
	<div class="verGap10"></div>
	<table class="tblEdit">
		<tr>
			<th class="thEdit">Additional Information</th>
		</tr>
		<tr>
			<td class="tdEdit"><%=CommonUtil.nvl(HtmlUtil.stringToHtml(uin.getAdditionalRemark()), "&nbsp;")%></td>
		</tr>
	</table>
	<div class="verGap10"></div>
	<table class="tblEdit" style="width:70%;">
		<colgroup>
			<col width="30%"></col>
			<col width="*"></col>
		</colgroup>
		<tr>
			<th class="thEdit" colspan="2">How To Pay</th>
		</tr>
		<tr>
			<th class="thEdit Rt">Bank</th>
			<td class="tdEdit"><%=CommonCodeManager.getCodeDescription("BANK_TYPE", uin.getBankCode())%></td>
		</tr>
		<tr>
			<th class="thEdit Rt">Name</th>
			<td class="tdEdit"><%=uin.getBankAccntName()%></td>
		</tr>
		<tr>
			<th class="thEdit Rt">BSB</th>
			<td class="tdEdit"><%=CommonUtil.getFormatString(uin.getBsb(), "??? ???")%></td>
		</tr>
		<tr>
			<th class="thEdit Rt">Account Number</th>
			<td class="tdEdit"><%=uin.getBankAccntNumber()%></td>
		</tr>
		<tr>
			<th class="thEdit Rt">Ref Number</th>
			<td class="tdEdit"><%=uin.getRefNumber()%></td>
		</tr>
	</table>
	<div class="verGap30"></div>
	<table class="tblDefault withPadding">
		<tr>
			<th class="thDefault">Should you have any questions, please contact above contact details.</th>
		</tr>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>