/**************************************************************************************************
 * project
 * Description - Rpu0202 - Profit And Loss Statement
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.rpu.rpu0202;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseBiz;
import project.common.extend.ReportPdfExportHelper;
import project.conf.resource.ormapper.dao.Report.ReportDao;
import zebra.data.DataSet;
import zebra.data.ParamEntity;
import zebra.data.QueryAdvisor;
import zebra.exception.FrameworkException;
import zebra.util.CommonUtil;
import zebra.util.ConfigUtil;

public class Rpu0202BizImpl extends BaseBiz implements Rpu0202Biz {
	@Autowired
	private ReportDao reportDao;

	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception {
		try {
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity getList(ParamEntity paramEntity) throws Exception {
		DataSet request = paramEntity.getRequestDataSet();
		QueryAdvisor qa = paramEntity.getQueryAdvisor();
		HttpSession session = paramEntity.getSession();
		String orgId = CommonUtil.nvl((String)session.getAttribute("OrgIdForAdminTool"), (String)session.getAttribute("OrgId"));

		try {
			qa.setObject("orgId", orgId);
			qa.setObject("financialYear", request.getValue("financialYear"));
			qa.setObject("quarterName", request.getValue("quarterName"));
			qa.setObject("fromDate", request.getValue("fromDate"));
			qa.setObject("toDate", request.getValue("toDate"));

			paramEntity.setAjaxResponseDataSet(reportDao.getProfitAndLoss(qa));
			paramEntity.setTotalResultRows(qa.getTotalResultRows());
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity doExport(ParamEntity paramEntity) throws Exception {
		DataSet request = paramEntity.getRequestDataSet();
		QueryAdvisor qa = paramEntity.getQueryAdvisor();
		ReportPdfExportHelper exportHelper;
		String dateFormat = ConfigUtil.getProperty("format.default.date");
		HttpSession session = paramEntity.getSession();
		String orgId = CommonUtil.nvl((String)session.getAttribute("OrgIdForAdminTool"), (String)session.getAttribute("OrgId"));
		DataSet srcData;

		try {
			qa.setObject("orgId", orgId);
			qa.setObject("financialYear", request.getValue("financialYear"));
			qa.setObject("quarterName", request.getValue("quarterName"));
			qa.setObject("fromDate", request.getValue("fromDate"));
			qa.setObject("toDate", request.getValue("toDate"));

			srcData = reportDao.getProfitAndLoss(qa);

			exportHelper = new ReportPdfExportHelper();
			exportHelper.setReportType("ProfitAndLoss");
			exportHelper.setFileType("pdf");
			exportHelper.setFileExtention("pdf");
			exportHelper.setFileName("ProfitAndLoss-"+orgId+"_"+CommonUtil.getSysdate(dateFormat));
			exportHelper.setSourceDataSet(srcData);
			exportHelper.setParamEntity(paramEntity);
			exportHelper.setQueryAdvisor(qa);

			paramEntity.setFileToExport(exportHelper.createFile());
			paramEntity.setFileNameToExport(exportHelper.getFileName());
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}
}